config/routes.rb
Betastore::Application.routes.draw do
  #resources :carts

  resources :subscriptions

  get '/products' => 'products#index'
  get '/customers' => 'customers#index'
  get '/products/:id' => 'products#show', as: "product"

  post '/products/:product_id/add_to_cart' => 'carts#update', as: 'add_to_cart'
  get '/cart' => 'carts#show', as: 'cart'

  put '/order' => 'orders#update', as: 'order'

  get '/checkout' => 'orders#new', as: 'checkout'
  post '/checkout' => 'orders#create' 

  namespace :admin do
     resources :products
     resources :customers

  get '/login' => 'logins#new', as: 'logins'
  post '/login' => 'logins#create'

  root :to => 'products#index'
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  has_many :line_items, :through => :orders
  has_many :products, :through => :line_items

  before_validation :downcase_email
  before_validation :upcase_state

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true, format: { with: \A@\z }
    validates :state, inclusion: { in: %w(AL AK AR AZ CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI 
      MN MS MO MT NE NH NV NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA DC WA WV WI WY),
      message: "%{value} is not a valid state" }
    validates :zip_code, length: { is: 5 }, allow_blank: true

  def upcase_state
      self.state = state.to_s.upcase
  end
       
  def downcase_email
      self.email = email.to_s.downcase
  end
end  

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.order('name')
  end

  def create
    @customer = Customer.new(customer.param)
  if @customer.save
    redirect_to admin_customer_path(@customer), notice: "Customer #{@customer.id} was created"
  else
    render 'new'
    end
  end

  def show
   @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end 

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  if @customer.update(customer.param)
    redirect_to admin_customers_path(@customer), notice: "Customer #{@customer.name} was updated successfully"
  else
    render 'edit'
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to admin_customers_path, notice: "Customer #{@customer.id} was deleted}"
  end

  private

  def product_params
  params.require(:product).permit(:email, :password)
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
def index
    @customers = Customer.order('name').where('name like ?', 'test%')
  end

  def show 
    @customers = Customer.find(params[:id])
  end

  def show
    @customers =Customer.edit(params[:id])
  end
end

app/views/admin/customers/edit.html.erb
<% if @customer.errors.present? %>
  <p>
    <h2>There was an error</h2>
    <% for error in @customer.errors.full_messages %>
    <%= error %>
    <% end %>
  </p>
<% end %>

<%= form_for [:admin, @customer] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </p>

  <p>
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </p>

  <%= f.submit %>
<% end %>

app/views/admin/customers/index.html.erb
<h1>Customers</h1>

<p><%= link_to "Add New Customer", new_admin_customer_path %></p>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>Created At</th>
    <th>Updated At</th>
    <th>State</th>
    <th>Zip Code</th>
  </tr>
  <% for customer in @customers %>
    <tr>
      <td><%= link_to customer.id, admin_customer_path(customer) %></td>
      <td><%= customer.name %></td>
      <td><%= customer.email%></td>
      <td><%= time_ago_in_words customer.created_at %> ago
      <%= customer.created_at.strftime('%A, %d %b %Y %l:%M %p') %></td>
      <td><%= time_ago_in_words customer.updated_at %> ago
      <%= customer.updated_at.strftime('%A, %d %b %Y %l:%M %p') %></td>
      <td><%= customer.state %></td>
      <td><%= customer.zip_code %></td>
    </tr>
  <% end %>
</table>

app/views/admin/customers/new.html.erb
<% if @customer.errors.present? %>
  <p>
    <h2>There was an error</h2>
    <% for error in @customer.errors.full_messages %>
    <%= error %>
    <% end %>
  </p>
<% end %>

<%= form_for [:admin, @customer] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email%>
    <%= f.text_field :email%>
  </p>

  <p>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </p>

  <p>
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </p>

  <%= f.submit %>
<% end %>

app/views/admin/customers/show.html.erb
<h1><%= @customer.name %></h1> 

<p> Email: <%= @customer.email %> </p>

 <p> <%= @customer.created_at.strftime('%A, %d %b %Y %l:%M %p') %> </p>

 <p> <%= @customer.updated_at.strftime('%A, %d %b %Y %l:%M %p') %> </p>

 <p> State: <%= @customer.state %> </p>

 <p> Zip Code: <%= @customer.zip_code %> </p>

 <p><%= link_to "Edit Customer", edit_admin_customer_path %></p>

 <p><%= link_to "Delete customer", admin_customer_path(@customer), method: :delete, data: { confirm: 'Are you sure you want to delete this customer?' } %> </p>

 <p><%= link_to "Back to Customer List", admin_customers_path %></p>