config/routes.rb
Betastore::Application.routes.draw do
  #resources :carts

  resources :subscriptions

  get '/products' => 'products#index'
  get '/customers' => 'customers#index'
  get '/products/:id' => 'products#show', as: "product"

  post '/products/:product_id/add_to_cart' => 'carts#update', as: 'add_to_cart'
  get '/cart' => 'carts#show', as: 'cart'

  put '/order' => 'orders#update', as: 'order'

  get '/checkout' => 'orders#new', as: 'checkout'
  post '/checkout' => 'orders#create' 

  namespace :admin do
     resources :products
     resources :customers

  get '/login' => 'logins#new', as: 'logins'
  post '/login' => 'logins#create'

  root :to => 'products#index'
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def update
    session[:cart] ||= {}
    cart = session[:cart]
    product_id = params[:product_id]

    if product_id.present?
      cart[product_id] ||= 0
      cart[product_id] += 1
    end
    redirect_to cart_path, alert: 'Item was added to cart'
  end

  def show
    @order = Order.new

    session[:cart].each do |product_id, quantity|
      @order.line_items.build(
        product: Product.find(product_id),
        quantity: quantity
      )
  end

  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Product carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<h1>Shopping Cart</h1>

<table class="table">
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Base Price</th>
    <th>Total Price</th>  
  </tr>
  <%= form_for @order, url: order_path, html: { method: 'put' } do |f| %>
    <%= f.fields_for :line_items do |li| %>
      <% line_item = li.object %>
      <%= li.hidden_field :product_id %>
    <tr>
      <td><%= line_item.product.name %></td>
      <td><%= li.number_field :quantity %></td>
      <td><%= number_to_currency line_item.product.price %></td>
      <td><%= number_to_currency line_item.total_price %></td>
    </tr>
    <% end %>
    <tr>
      <td colspan="3">
        <%= f.submit "Update Cart", class: 'btn btn-success' %>
        <%= link_to "Checkout", checkout_path, class: 'btn btn-success' %>
      </td>
      <td><%= number_to_currency @order.total_price %></td>
    </tr>
  <% end %>
</table>