config/routes.rb
Betastore::Application.routes.draw do
  #resources :carts

  resources :subscriptions

  get '/products' => 'products#index'
  get '/customers' => 'customers#index'
  get '/products/:id' => 'products#show', as: "product"

  post '/products/:product_id/add_to_cart' => 'carts#update', as: 'add_to_cart'
  get '/cart' => 'carts#show', as: 'cart'

  put '/order' => 'orders#update', as: 'order'

  get '/checkout' => 'orders#new', as: 'checkout'
  post '/checkout' => 'orders#create' 

  namespace :admin do
     resources :products
     resources :customers

  get '/login' => 'logins#new', as: 'logins'
  post '/login' => 'logins#create'

  root :to => 'products#index'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, :through => :line_items

  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

before_destroy :ensure_not_referenced_by_any_line_item  

private

# ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  
  before_action :require_login

  def index
    if logged_in?
     @products = Product.order('name').to_a
    else
     redirect_to admin_logins_path, alert: 'Please log in to continue'
    end
  end


  def create
    @product = Product.new(product_params)
  if @product.save
    redirect_to admin_product_path(@product), notice: "Product #{@product.id} was created"
  else
    render 'new'
    end
  end

  def show
   @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end 

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
  if @product.update(product_params)
    redirect_to admin_products_path(@product), notice: "Product #{@product.name} was updated successfully"
  else
    render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path, notice: "Product #{@product.id} was deleted}"
  end
  
  private

  def logged_in?
  session[:user_id].present?
end

  def product_params
  params.require(:product).permit(:name, :price)
end

  def require_login
  unless logged_in?
    redirect_to admin_login_path, danger: 'Please log in to continue'
  end
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order('name')
  end

  def show 
    @product = Product.find(params[:id])

  end

end

app/views/admin/products/_form.html.erb
<% if @product.errors.present? %>
  <p>
    <h2>There was an error</h2>
    <% for error in @product.errors.full_messages %>
    <%= error %>
    <% end %>
  </p>
<% end %>

<%= form_for [:admin, @product], html: {class: "form-horizontal", role: "form"} do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label"  %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <%= f.text_field :price %>
  </div>

  <div class="form-group">
    <%= f.label :image_url, class: "col-sm-2 control-label" %>
    <%= f.url_field :image_url %>
  </div>

  <div class="form-group">
    <%= f.submit "Update Product", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<ol class="breadcrumb">
<li><%= link_to "Products", admin_products_path %></li>
<li><%= link_to @product.name, admin_product_path(@product) %></li>
<li class="active">Edit Product</li>
</ol>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<h1>Products</h1>

<p><%= link_to "Add New Product", new_admin_product_path, class: 'btn btn-primary' %></p>

<table class="table">
<table class="table table-striped">
 
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Price</th>
    <th>Created At</th>
  </tr>
  <% for product in @products %>
    <tr>
      <td><%= link_to product.id, admin_product_path(product) %></td>
      <td><%= link_to product.name, admin_product_path(product) %></td>
      <td><%= number_to_currency product.price %></td>
      <td><%= time_ago_in_words product.created_at %> ago
      <%= product.created_at.strftime('%A, %d %b %Y %l:%M %p') %></td>
    </tr>
  <% end %>
</table>

app/views/admin/products/new.html.erb
<ol class="breadcrumb">
<li><%= link_to "Products", admin_products_path %></li>
<li class="active">New Product</li>
</ol>

<%= render 'form' %>

app/views/admin/products/show.html.erb
<ol class="breadcrumb">
<h1><%= @product.name %></h1>

<p>
  Price: <%= number_to_currency @product.price %> </p>

 
<%= form_for [:admin, @product], html: {class: "form-horizontal", role: "form"} do |f| %>
 <p>
 <%= image_tag @product.image_url, alt: @product.name,
    style: 'max_width: 500px' %></p>

<div class="form-group">
  <%= @product.created_at.strftime('%A, %d %b %Y %l:%M %p') %> 
</div>

<div class="form-group">
  <%= link_to "Edit Product", edit_admin_product_path, class: 'btn btn-success' %>
</div>

<div class="form-group">
  <%= link_to "Delete product", admin_product_path(@product), method: :delete, data: { confirm: 'Are you sure you want to delete this product?' }, class: 'btn btn-success' %>
</div>

<div class="form-group">
  <%= link_to "Back to Product List", admin_products_path, class: 'btn btn-success'  %>
</div>
<% end %>
</ol>